# Generated by Django 5.2.1 on 2026-06-10 05:34

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/photos/', validators=[App.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/', validators=[App.models.validate_file_extension]),
        ),
    ]
