# Generated by Django 5.2.1 on 2026-06-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_newsletter_alter_galleryitem_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='NewsletterSubscriber',
        ),
    ]
