# Generated by Django 5.2.1 on 2026-06-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_rename_newsletter_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'verbose_name': 'Newsletter Subscriber', 'verbose_name_plural': 'Newsletter Subscribers'},
        ),
    ]
