# Generated by Django 5.2.1 on 2026-06-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_newsupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsupdate',
            options={'ordering': ['-date', '-id']},
        ),
    ]
