# Generated by Django 5.2.1 on 2026-06-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_otpverification_studentapplication_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='password_choice',
            field=models.CharField(choices=[('auto', 'Auto-Generate Password'), ('custom', 'Custom Password')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='reminder_count',
            field=models.IntegerField(default=0),
        ),
    ]
